blank_issues_enabled: false
contact_links:
  - name: Ask a question
    url: https://github.com/Lawrenceku/Mooz/issues/new?labels=question
    about: Not a bug or a feature request? Just open a question issue.
